const libtaichi = Ref{String}("")

# API generated by misc/generate_julia_api.jl

include("generated/TaichiPlatform.jl")
include("generated/TaichiCore.jl")
include("generated/TaichiCpu.jl")
include("generated/TaichiCuda.jl")
include("generated/TaichiMetal.jl")
include("generated/TaichiOpengl.jl")
include("generated/TaichiUnity.jl")
include("generated/TaichiVulkan.jl")
